### ISSUE TITLE
Stormcows broken in TB 38.2.0 / Lightning 4.0.2

### ISSUE THREAD

**Issue by GAJansen** [moldybeats/stormcows#12]
After upgrading Thunderbird to version 38.2.0 (and the obligatory update of Lightning to version 4.0.2), My stormcows items are no longer loaded. In the calendar list, the relevant calendars seem to be active (checked as beeing 'on'), but a yellow triangle with an exclamation mark indicates an error.
Switching the calendars on and off does not help, nor does removal and reselecting using the stormcows window. The issue occurs both under Win7 and Ubuntu 15.04. Any ideas how to solve this?

**Comment by moldybeats** [comment]
Thanks for the report. I just got the update to TB38 and I'm seeing the same thing.

Unfortunately, I'm not really using Thunderbird these days, to be honest. But I'll try to take a look soon and see if there's an easy fix.

**Comment by housepawsjohn** [comment]
I'm still using TB 31.7 for this very reason.
I have not had the time to try bypassing StormCows and using .dav 
functionality directly to attempt to achieve the same effect.

**Comment by moldybeats** [comment]
I just committed some changes that should allow StormCows to work with TB38 and Lightning 4.0.2:
https://github.com/moldybeats/stormcows/commit/24b820e9ba5153f39d4bf6e198afe697ffe9196e

I've submitted the updated version of StormCows (version 0.4) to Mozilla and it's pending their review & approval, so it might be a few days(?) before the update shows up for you inside Thunderbird.

I'm going to close this issue, but if anyone is still having issues after updating to version 0.4, please let me know.

**Comment by GAJansen** [comment]
The update of StormCows (version 0.4) works like a charm.
Thanks for that moldybeats!
